version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: aigis
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 18080:8080
  redis:
    image: redis:5
    restart: always
    ports:
      - 6379:6379
